version: '3.9'

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DATA_VOL_DEVICE:-:/openldap-data-vol/}

  config-vol:
    name: ${CONFIG_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CONFIG_VOL_DEVICE:-:/openldap-config-vol/}
