version: '3.5'

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  config-vol:
    name: ${CONFIG_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
